### ISSUE TITLE
Adding 0 to infront of the digits such that it keeps 6 digits.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Score-Display-Pinball#5]
Need to add 0s infront of the number in the displayDigits array.

Because right now

it stores 8353 instead of 008353.

So, need to implement the logic to add 0s infront of the number.

**Comment by kwelsch7** [comment]
If all else fails, it can be done in one line of C code (and a header). ;)
#include <stdio.h>
sprintf(displayDigits[displayNumber], "%06lu", displayVal[displayNumber]);
